name: Run screener and publish CSV

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: screener-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DEFAULT_BRANCH: 'main'   # change en 'master' si besoin
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure clean working tree (sync to origin/main)
        run: |
          git fetch origin $DEFAULT_BRANCH
          git reset --hard origin/$DEFAULT_BRANCH
          git clean -fd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        run: python gen_r2000_from_ishares.py || true

      - name: Build sector catalog (R1K + SPSM)
        run: python build_sector_catalog.py || true

      - name: Run screener
        env:
          PYTHONUNBUFFERED: "1"
        run: python mix_ab_screen_indices.py

      - name: Run backtest
        run: python backtest_signals.py

      - name: Fetch Fear & Greed (CNN)
        run: python fetch_fear_greed.py

      - name: Commit CSVs if changed
        run: |
          set -e
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes, skip commit"
            exit 0
          fi

          git add *.csv dashboard/public/*.csv || true
          git -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
              commit -m "auto: update CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true

          git fetch origin $DEFAULT_BRANCH
          git merge -s recursive -X ours origin/$DEFAULT_BRANCH || true
          git push origin HEAD:$DEFAULT_BRANCH || true

          echo "--- git status ---"
          git status --porcelain
