name: Run screener and publish CSV

on:
  schedule:
    # Toutes les heures à hh:07 UTC (GitHub Actions est en UTC)
    - cron: "7 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # nécessaire pour rebase/pull propre

      - name: Ensure clean working tree (sync to origin/main)
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        run: |
          python gen_r2000_from_ishares.py

      - name: Build sector catalog (R1K + SPSM)
        run: |
           python build_sector_catalog.py || true

      - name: Run screener
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python mix_ab_screen_indices.py
          
      - name: Run backtest
        run: |
          python backtest_signals.py
       
      - name: Commit CSVs if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1) Récupère la dernière main SANS rebase et en privilégiant nos fichiers en cas de conflit
          git fetch origin main
          git merge -s recursive -X ours origin/main || true

          # 2) Ajoute tout ce qui nous intéresse (racine + dashboard/public)
          git add *.csv dashboard/public/*.csv || true

          # 3) Commit si besoin
          git commit -m "auto: update CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true

          # 4) Push
          git push origin HEAD:main || true

          # 5) (optionnel) statut pour debug
          echo "--- git status ---"
          git status --porcelain
