name: Run screener and publish CSV

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
  
      - name: Checkout repo
        if: env.RUN == '1'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure clean working tree (sync to origin/main)
        if: env.RUN == '1'
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Setup Python
        if: env.RUN == '1'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: env.RUN == '1'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        if: env.RUN == '1'
        run: python gen_r2000_from_ishares.py || true

      - name: Build sector catalog (R1K + SPSM)
        if: env.RUN == '1'
        run: python build_sector_catalog.py || true

      - name: Run screener
        if: env.RUN == '1'
        env:
          PYTHONUNBUFFERED: "1"
        run: python mix_ab_screen_indices.py

      - name: Run backtest
        if: env.RUN == '1'
        run: python backtest_signals.py

      - name: Fetch Fear & Greed (CNN)
        if: env.RUN == '1'
        run: python fetch_fear_greed.py

      - name: Commit CSVs if changed
        if: env.RUN == '1'
        run: |
          set -e
          # plus fiable que git diff --quiet : détecte aussi les fichiers non suivis
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes, skip commit"
            exit 0
          fi

          git add *.csv dashboard/public/*.csv || true
          git -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
              commit -m "auto: update CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true

          git fetch origin main
          git merge -s recursive -X ours origin/main || true
          git push origin HEAD:main || true

          echo "--- git status ---"
          git status --porcelain
