name: Run screener and publish CSV

on:
  schedule:
    # Toutes les 4 heures à HH:00 UTC
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure clean working tree (sync to origin/main)
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        run: python gen_r2000_from_ishares.py

      - name: Build sector catalog (R1K + SPSM)
        run: python build_sector_catalog.py || true

      - name: Run screener
        env:
          PYTHONUNBUFFERED: "1"
        run: python mix_ab_screen_indices.py

      - name: Run backtest
        run: python backtest_signals.py

      - name: Fetch Fear & Greed (CNN)
        run: python fetch_fear_greed.py

      - name: Commit CSVs if changed
        run: |
          set -e

          # Configure git (avant tout commit)
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Ajouter tout (y compris nouveaux fichiers)
          git add -A

          # Si rien à committer -> on quitte proprement
          if git diff --cached --quiet; then
            echo "No changes, skip commit."
            exit 0
          fi

          # Se resynchroniser et garder nos fichiers en cas de conflit
          git fetch origin main
          git merge -s recursive -X ours --no-edit origin/main || true

          # Commit unique + push
          git commit -m "auto: update CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:main

          echo "--- git status ---"
          git status --porcelain
