name: Run screener and publish CSV

on:
  schedule:
    # Toutes les heures à hh:07 UTC (GitHub Actions est en UTC)
    - cron: "7 * * * *"
  workflow_dispatch: {}  # pour lancer à la main si besoin

permissions:
  contents: write  # pour pouvoir commit dans le repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        run: |
          python gen_r2000_from_ishares.py

      - name: Run screener
        env:
          # (optionnel) variable pour réduire la cadence si tu veux (ton script a déjà un petit sleep)
          PYTHONUNBUFFERED: "1"
        run: |
          python mix_ab_screen_indices.py

      - name: Commit CSVs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || git rebase --abort
          git add *.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "auto: update CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:main
          else
            echo "No CSV changes."
          fi
