name: Run screener and publish CSV

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: screener-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DEFAULT_BRANCH: 'main'   # change en 'master' si besoin
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure clean working tree (sync to origin)
        run: |
          set -euo pipefail
          git fetch origin $DEFAULT_BRANCH
          git reset --hard origin/$DEFAULT_BRANCH
          git clean -fd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Russell2000 from iShares
        run: python gen_r2000_from_ishares.py || true

      - name: Build sector catalog (R1K + SPSM)
        run: python build_sector_catalog.py || true

      - name: Run screener
        env:
          PYTHONUNBUFFERED: "1"
        run: python mix_ab_screen_indices.py

      - name: Run backtest
        run: python backtest_signals.py

      - name: Fetch Fear & Greed (root CSV/JSON)
        run: |
          set -euo pipefail
          python fetch_fear_greed.py

      - name: Sanity check CSVs (root + dashboard/public)
        run: |
          set -euo pipefail
          echo "== ROOT files =="
          ls -lah || true
          echo "---- head fear_greed.csv (root) ----"
          head -n 20 fear_greed.csv || (echo "missing root fear_greed.csv" && exit 1)
          echo "---- head fear_greed_history.csv (root) ----"
          head -n 5 fear_greed_history.csv || true
          echo "---- head fear_greed.json (root) ----"
          head -n 5 fear_greed.json || true

          echo "== dashboard/public =="
          ls -lah dashboard/public || true
          echo "---- head backtest_summary.csv ----"
          head -n 20 dashboard/public/backtest_summary.csv || true
          echo "---- head confirmed_STRONGBUY.csv ----"
          head -n 5 dashboard/public/confirmed_STRONGBUY.csv || true

          echo "== GIT STATUS =="
          git status --porcelain

      - name: Commit & push CSV updates
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi
          git commit -m "auto: update CSVs (fear_greed + others)"
          git pull --rebase origin $DEFAULT_BRANCH
          git push origin HEAD:$DEFAULT_BRANCH
